// Package envfiles generates the PATH helper files of a project or the
// global scope (Spec §14.2).
package envfiles

import (
	"os"
	"path/filepath"
	"strings"
)

// WriteProject writes .agents/env.sh and .agents/env.ps1 into a project.
// The shell script locates itself under bash (BASH_SOURCE), zsh (prompt %N
// expansion), and falls back to $0 elsewhere.
func WriteProject(projectRoot string) error {
	agentsDir := filepath.Join(projectRoot, ".agents")
	if err := os.MkdirAll(agentsDir, 0o755); err != nil {
		return err
	}
	envSh := "# Generated by Curator. Do not edit.\n" +
		"if [ -n \"${BASH_SOURCE:-}\" ]; then\n" +
		"  _curator_env_path=\"${BASH_SOURCE[0]}\"\n" +
		"elif [ -n \"${ZSH_VERSION:-}\" ]; then\n" +
		"  _curator_env_path=\"${(%):-%N}\"\n" +
		"else\n" +
		"  _curator_env_path=\"$0\"\n" +
		"fi\n" +
		"CSK_PROJECT_ROOT=\"$(cd \"$(dirname \"$_curator_env_path\")/..\" && pwd)\"\n" +
		"unset _curator_env_path\n" +
		"export CSK_PROJECT_ROOT\n" +
		"export PATH=\"$CSK_PROJECT_ROOT/.agents/bin:$PATH\"\n"
	if err := os.WriteFile(filepath.Join(agentsDir, "env.sh"), []byte(envSh), 0o644); err != nil {
		return err
	}
	envPs1 := "# Generated by Curator. Do not edit.\n" +
		"$CuratorAgentsDir = Split-Path -Parent $MyInvocation.MyCommand.Path\n" +
		"$CuratorProjectRoot = Split-Path -Parent $CuratorAgentsDir\n" +
		"$env:CSK_PROJECT_ROOT = $CuratorProjectRoot\n" +
		"$env:PATH = \"$CuratorProjectRoot\\.agents\\bin;$env:PATH\"\n"
	return os.WriteFile(filepath.Join(agentsDir, "env.ps1"), []byte(envPs1), 0o644)
}

// WriteGlobal writes the global env files exporting CSK_GLOBAL_ROOT.
func WriteGlobal(home string) error {
	globalDir := filepath.Join(home, "global")
	if err := os.MkdirAll(filepath.Join(globalDir, "bin"), 0o755); err != nil {
		return err
	}
	envSh := "# Generated by Curator. Do not edit.\n" +
		"export CSK_GLOBAL_ROOT=" + shQuote(globalDir) + "\n" +
		"export PATH=\"$CSK_GLOBAL_ROOT/bin:$PATH\"\n"
	if err := os.WriteFile(filepath.Join(globalDir, "env.sh"), []byte(envSh), 0o644); err != nil {
		return err
	}
	envPs1 := "# Generated by Curator. Do not edit.\n" +
		"$env:CSK_GLOBAL_ROOT = " + psQuote(globalDir) + "\n" +
		"$env:PATH = \"$env:CSK_GLOBAL_ROOT\\bin;$env:PATH\"\n"
	return os.WriteFile(filepath.Join(globalDir, "env.ps1"), []byte(envPs1), 0o644)
}

func shQuote(value string) string {
	return "'" + strings.ReplaceAll(value, "'", `'"'"'`) + "'"
}

func psQuote(value string) string {
	return "'" + strings.ReplaceAll(value, "'", "''") + "'"
}
