// Package envfiles generates the PATH helper files of a project or the
// global scope (Spec §14.2).
package envfiles

import (
	"os"
	"path/filepath"
	"strings"
)

// Names of the generated helper files inside a scope's env directory.
const (
	ShellName      = "env.sh"
	PowerShellName = "env.ps1"
)

// ProjectContent returns the exact bytes of the two project helper files.
// The shell script locates itself under bash (BASH_SOURCE), zsh (prompt %N
// expansion), and falls back to $0 elsewhere.
func ProjectContent() (shell, powerShell []byte) {
	envSh := "# Generated by Curator. Do not edit.\n" +
		"if [ -n \"${BASH_SOURCE:-}\" ]; then\n" +
		"  _curator_env_path=\"${BASH_SOURCE[0]}\"\n" +
		"elif [ -n \"${ZSH_VERSION:-}\" ]; then\n" +
		"  _curator_env_path=\"${(%):-%N}\"\n" +
		"else\n" +
		"  _curator_env_path=\"$0\"\n" +
		"fi\n" +
		"CSK_PROJECT_ROOT=\"$(cd \"$(dirname \"$_curator_env_path\")/..\" && pwd)\"\n" +
		"unset _curator_env_path\n" +
		"export CSK_PROJECT_ROOT\n" +
		"export PATH=\"$CSK_PROJECT_ROOT/.agents/bin:$PATH\"\n"
	envPs1 := "# Generated by Curator. Do not edit.\n" +
		"$CuratorAgentsDir = Split-Path -Parent $MyInvocation.MyCommand.Path\n" +
		"$CuratorProjectRoot = Split-Path -Parent $CuratorAgentsDir\n" +
		"$env:CSK_PROJECT_ROOT = $CuratorProjectRoot\n" +
		"$env:PATH = \"$CuratorProjectRoot\\.agents\\bin;$env:PATH\"\n"
	return []byte(envSh), []byte(envPs1)
}

// GlobalContent returns the exact bytes of the two global helper files.
func GlobalContent(home string) (shell, powerShell []byte) {
	globalDir := filepath.Join(home, "global")
	envSh := "# Generated by Curator. Do not edit.\n" +
		"if [ -n \"${BASH_SOURCE:-}\" ]; then\n" +
		"  _curator_global_env_path=\"${BASH_SOURCE[0]}\"\n" +
		"elif [ -n \"${ZSH_VERSION:-}\" ]; then\n" +
		"  _curator_global_env_path=\"${(%):-%N}\"\n" +
		"else\n" +
		"  _curator_global_env_path=\"$0\"\n" +
		"fi\n" +
		"CSK_GLOBAL_ROOT=\"$(cd \"$(dirname \"$_curator_global_env_path\")\" && pwd)\"\n" +
		"unset _curator_global_env_path\n" +
		"export CSK_GLOBAL_ROOT\n" +
		"export PATH=\"$CSK_GLOBAL_ROOT/bin:$PATH\"\n"
	envPs1 := "# Generated by Curator. Do not edit.\n" +
		"$env:CSK_GLOBAL_ROOT = " + psQuote(globalDir) + "\n" +
		"$env:PATH = \"$env:CSK_GLOBAL_ROOT\\bin;$env:PATH\"\n"
	return []byte(envSh), []byte(envPs1)
}

// ProjectDir is the directory that holds a project's helper files.
func ProjectDir(projectRoot string) string { return filepath.Join(projectRoot, ".agents") }

// GlobalDir is the directory that holds the global scope's helper files.
func GlobalDir(home string) string { return filepath.Join(home, "global") }

// WriteProject writes .agents/env.sh and .agents/env.ps1 into a project.
//
// It mutates live paths directly and therefore belongs only to callers outside
// an install transaction, such as scaffolding a checkout. An installation
// stages the same bytes through StageProject and lets the commit phase publish
// them atomically.
func WriteProject(projectRoot string) error {
	agentsDir := ProjectDir(projectRoot)
	if err := os.MkdirAll(agentsDir, 0o755); err != nil {
		return err
	}
	shell, powerShell := ProjectContent()
	if err := os.WriteFile(filepath.Join(agentsDir, ShellName), shell, 0o644); err != nil {
		return err
	}
	return os.WriteFile(filepath.Join(agentsDir, PowerShellName), powerShell, 0o644)
}

// WriteGlobal writes the global env files exporting CSK_GLOBAL_ROOT. Like
// WriteProject it is the direct-mutation form; StageGlobal is the install form.
func WriteGlobal(home string) error {
	globalDir := GlobalDir(home)
	if err := os.MkdirAll(filepath.Join(globalDir, "bin"), 0o755); err != nil {
		return err
	}
	shell, powerShell := GlobalContent(home)
	if err := os.WriteFile(filepath.Join(globalDir, ShellName), shell, 0o644); err != nil {
		return err
	}
	return os.WriteFile(filepath.Join(globalDir, PowerShellName), powerShell, 0o644)
}

func psQuote(value string) string {
	return "'" + strings.ReplaceAll(value, "'", "''") + "'"
}
