package yarnclassicsource

import (
	"archive/tar"
	"bytes"
	"compress/gzip"
	"context"
	"crypto/sha512"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"io/fs"
	"os"
	"os/exec"
	"path/filepath"
	"reflect"
	"sort"
	"strings"
	"testing"
	"time"

	"github.com/relux-works/curator/internal/artifactpolicy"
	"github.com/relux-works/curator/internal/closureexec"
	"github.com/relux-works/curator/internal/closuregraph"
	"github.com/relux-works/curator/internal/nodesource"
)

type fixturePackage struct {
	name, version string
	metadata      map[string]any
	files         map[string][]byte
}

type yarnFixture struct {
	root, work string
	request    ParseRequest
	tarballs   map[string]RawTarball
	payloads   map[string][]byte
	graph      Graph
}

func newYarnFixture(t *testing.T) yarnFixture {
	t.Helper()
	root := filepath.Join(t.TempDir(), "project")
	work := filepath.Join(t.TempDir(), "capture-work")
	if err := os.MkdirAll(filepath.Join(root, "packages", "workspace"), 0o700); err != nil {
		t.Fatal(err)
	}
	rootManifest := map[string]any{"name": "app", "version": "1.0.0", "private": true, "workspaces": map[string]any{"packages": []string{"packages/*"}, "nohoist": []string{"workspace/b"}}, "dependencies": map[string]string{"a": "^1.0.0", "workspace": "1.0.0"}, "optionalDependencies": map[string]string{"opt": "^1.0.0"}}
	workspaceManifest := map[string]any{"name": "workspace", "version": "1.0.0", "dependencies": map[string]string{"b": "^1.0.0"}}
	packages := []fixturePackage{
		{name: "a", version: "1.0.0", metadata: map[string]any{"dependencies": map[string]string{"b": "^1.0.0"}}, files: map[string][]byte{"index.js": []byte("module.exports=require('b')\n")}},
		{name: "b", version: "1.0.0", metadata: map[string]any{}, files: map[string][]byte{"index.js": []byte("module.exports='b'\n")}},
		{name: "opt", version: "1.0.0", metadata: map[string]any{"os": []string{"linux"}}, files: map[string][]byte{"index.js": []byte("module.exports='opt'\n")}},
	}
	entries := []string{}
	payloadByName := map[string][]byte{}
	pathByName := map[string]string{}
	for _, pkg := range packages {
		payload := buildTGZ(t, pkg)
		sum := sha512.Sum512(payload)
		integrity := "sha512-" + base64.StdEncoding.EncodeToString(sum[:])
		resolved := fmt.Sprintf("https://registry.yarnpkg.com/%s/-/%s-%s.tgz#pinned", pkg.name, pkg.name, pkg.version)
		entry := fmt.Sprintf("%s@^1.0.0:\n  version \"%s\"\n  resolved \"%s\"\n  integrity %s\n", pkg.name, pkg.version, resolved, integrity)
		if dependencies, ok := pkg.metadata["dependencies"].(map[string]string); ok {
			entry += "  dependencies:\n"
			for _, name := range sortedMapKeys(dependencies) {
				entry += fmt.Sprintf("    %s \"%s\"\n", name, dependencies[name])
			}
		}
		entries = append(entries, entry)
		payloadByName[pkg.name] = payload
		file := filepath.Join(t.TempDir(), pkg.name+"-1.0.0.tgz")
		if err := os.WriteFile(file, payload, 0o600); err != nil {
			t.Fatal(err)
		}
		pathByName[pkg.name] = file
	}
	lockBytes := []byte("# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.\n# yarn lockfile v1\n\n" + strings.Join(entries, "\n"))
	rootBytes := mustJSON(t, rootManifest)
	workspaceBytes := mustJSON(t, workspaceManifest)
	writeFile(t, filepath.Join(root, "package.json"), rootBytes)
	writeFile(t, filepath.Join(root, "yarn.lock"), lockBytes)
	writeFile(t, filepath.Join(root, "index.js"), []byte("require('a')\n"))
	writeFile(t, filepath.Join(root, "packages", "workspace", "package.json"), workspaceBytes)
	writeFile(t, filepath.Join(root, "packages", "workspace", "index.js"), []byte("require('b')\n"))
	request := ParseRequest{LockName: "yarn.lock", LockBytes: lockBytes, Manifests: map[string][]byte{"package.json": rootBytes, "packages/workspace/package.json": workspaceBytes}, YarnVersion: SupportedYarnVersion, AllowedRegistryOrigins: []string{"https://registry.yarnpkg.com/"}, Target: Target{OS: "darwin", Architecture: "arm64", Libc: "none", IncludeDev: true}}
	graph, err := Parse(request)
	if err != nil {
		t.Fatal(err)
	}
	tarballs := map[string]RawTarball{}
	payloads := map[string][]byte{}
	for _, pkg := range graph.Packages {
		if pkg.Resolved != "" {
			tarballs[pkg.Key] = RawTarball{Path: pathByName[pkg.Name]}
			payloads[pkg.Key] = payloadByName[pkg.Name]
		}
	}
	return yarnFixture{root: root, work: work, request: request, tarballs: tarballs, payloads: payloads, graph: graph}
}

func TestS01N01ClosedYarnLockWorkspaceVersionLayoutAndCapture(t *testing.T) {
	fixture := newYarnFixture(t)
	if fixture.graph.YarnVersion != SupportedYarnVersion || fixture.graph.Layout.ModulesFolder != "node_modules" || !reflect.DeepEqual(fixture.graph.Layout.Nohoist, []string{"workspace/b"}) || len(fixture.graph.Workspaces) != 1 {
		t.Fatalf("closed Yarn identity/layout missing: %+v", fixture.graph)
	}
	capture := captureFixture(t, fixture)
	if capture.Evidence.ProfileID != ProfileID || len(capture.Evidence.Tarballs) != 3 || !capture.Evidence.NodeCaptureGraphID.Valid() {
		t.Fatalf("capture evidence incomplete: %+v", capture.Evidence)
	}
	if len(capture.NodeCapture.Graph.RootNodeIDs) != 1 {
		t.Fatalf("unexpected root graph: %+v", capture.NodeCapture.Graph)
	}
	optional := packageByName(t, capture.Graph, "opt")
	if optional.Selected || optional.PruneReason != "os_pruned" {
		t.Fatalf("target-pruned optional package not retained deterministically: %+v", optional)
	}
}

func TestS06CanonicalOrderN02StaleN03IntegrityAndExactVersion(t *testing.T) {
	fixture := newYarnFixture(t)
	sections := strings.Split(strings.TrimSpace(string(fixture.request.LockBytes)), "\n\n")
	permuted := append([]string(nil), sections[:2]...)
	for i := len(sections) - 1; i >= 2; i-- {
		permuted = append(permuted, sections[i])
	}
	request := fixture.request
	request.LockBytes = []byte(strings.Join(permuted, "\n\n") + "\n")
	graph, err := Parse(request)
	if err != nil {
		t.Fatal(err)
	}
	if graph.LockDigest != fixture.graph.LockDigest || graph.RawLockSHA256 == fixture.graph.RawLockSHA256 {
		t.Fatalf("semantic/raw lock identity separation failed")
	}
	t.Run("stale manifest", func(t *testing.T) {
		request := fixture.request
		var manifest map[string]any
		_ = json.Unmarshal(request.Manifests["package.json"], &manifest)
		manifest["dependencies"].(map[string]any)["a"] = "^2.0.0"
		request.Manifests = cloneBytesMap(request.Manifests)
		request.Manifests["package.json"] = mustJSON(t, manifest)
		_, err := Parse(request)
		assertCode(t, err, CodeLockStale)
	})
	t.Run("exact manager version", func(t *testing.T) {
		request := fixture.request
		request.YarnVersion = "1.22.21"
		_, err := Parse(request)
		assertCode(t, err, CodeLockFormatUnsupported)
	})
	t.Run("integrity mutation", func(t *testing.T) {
		fixture := newYarnFixture(t)
		for key, raw := range fixture.tarballs {
			payload := append([]byte(nil), fixture.payloads[key]...)
			payload[len(payload)-1] ^= 1
			writeFile(t, raw.Path, payload)
			break
		}
		_, err := captureFixtureError(t, fixture)
		assertCode(t, err, CodeIntegrityMismatch)
	})
}

func TestN04N06N11LifecycleNativeCompiledAndSubtreeLockFailClosed(t *testing.T) {
	t.Run("lifecycle", func(t *testing.T) {
		fixture := newYarnFixture(t)
		replaceFixturePackage(t, &fixture, "a", fixturePackage{name: "a", version: "1.0.0", metadata: map[string]any{"dependencies": map[string]string{"b": "^1.0.0"}, "scripts": map[string]string{"postinstall": "node install.js"}}, files: map[string][]byte{"index.js": []byte("module.exports=1\n")}})
		_, err := captureFixtureError(t, fixture)
		assertCode(t, err, CodeHookUndeclared)
	})
	t.Run("binding gyp", func(t *testing.T) {
		fixture := newYarnFixture(t)
		replaceFixturePackage(t, &fixture, "a", fixturePackage{name: "a", version: "1.0.0", metadata: map[string]any{"dependencies": map[string]string{"b": "^1.0.0"}}, files: map[string][]byte{"binding.gyp": []byte("{'targets': []}\n")}})
		_, err := captureFixtureError(t, fixture)
		assertCode(t, err, CodeNativeBuildUnsupported)
	})
	t.Run("compiled payload", func(t *testing.T) {
		fixture := newYarnFixture(t)
		replaceFixturePackage(t, &fixture, "a", fixturePackage{name: "a", version: "1.0.0", metadata: map[string]any{"dependencies": map[string]string{"b": "^1.0.0"}}, files: map[string][]byte{"renamed.txt": {0, 0x61, 0x73, 0x6d, 1, 0, 0, 0}}})
		_, err := captureFixtureError(t, fixture)
		if artifactpolicy.ErrorCode(err) != artifactpolicy.CodeCompiledDependency {
			t.Fatalf("compiled diagnostic=%v code=%s", err, artifactpolicy.ErrorCode(err))
		}
	})
	t.Run("subtree lock", func(t *testing.T) {
		fixture := newYarnFixture(t)
		writeFile(t, filepath.Join(fixture.root, "packages", "workspace", "yarn.lock"), fixture.request.LockBytes)
		_, err := captureFixtureError(t, fixture)
		assertCode(t, err, CodeLockStale)
	})
}

func TestCaptureDiscoversWorkspaceAndConfigurationAuthorityBeforeYarnStarts(t *testing.T) {
	t.Run("glob expanded workspace omitted by caller", func(t *testing.T) {
		fixture := newYarnFixture(t)
		runner := &fakeYarnRunner{}
		if err := os.MkdirAll(filepath.Join(fixture.root, "packages", "extra"), 0o700); err != nil {
			t.Fatal(err)
		}
		extra := filepath.Join(fixture.root, "packages", "extra", "package.json")
		writeFile(t, extra, mustJSON(t, map[string]any{"name": "extra", "version": "1.0.0"}))
		_, err := captureFixtureError(t, fixture)
		assertCode(t, err, CodeLockStale)
		if runner.starts != 0 {
			t.Fatalf("workspace authority failure started Yarn %d times", runner.starts)
		}
	})
	t.Run("parsed workspace missing from immutable tree", func(t *testing.T) {
		fixture := newYarnFixture(t)
		if err := os.Remove(filepath.Join(fixture.root, "packages", "workspace", "package.json")); err != nil {
			t.Fatal(err)
		}
		_, err := captureFixtureError(t, fixture)
		assertCode(t, err, CodeLockStale)
	})
	for _, config := range []string{".yarnrc", ".npmrc", ".yarnrc.yml", "packages/workspace/.yarnrc"} {
		t.Run("omitted config "+strings.ReplaceAll(config, "/", "_"), func(t *testing.T) {
			fixture := newYarnFixture(t)
			writeFile(t, filepath.Join(fixture.root, filepath.FromSlash(config)), []byte("--install.modules-folder ambient_modules\n"))
			_, err := captureFixtureError(t, fixture)
			assertCode(t, err, CodeLockStale)
		})
	}
	t.Run("declared root configuration is bijective", func(t *testing.T) {
		fixture := newYarnFixture(t)
		configuration := []byte("modules-folder vendor_modules\nworkspaces-experimental true\n")
		writeFile(t, filepath.Join(fixture.root, ".yarnrc"), configuration)
		fixture.request.Configuration = map[string][]byte{".yarnrc": configuration}
		graph, err := Parse(fixture.request)
		if err != nil {
			t.Fatal(err)
		}
		fixture.graph = graph
		capture := captureFixture(t, fixture)
		if capture.Graph.Layout.ModulesFolder != "vendor_modules" {
			t.Fatalf("declared layout was not captured: %+v", capture.Graph.Layout)
		}
	})
}

func TestN12MissingMirrorArtifactFailsBeforeYarnAndPublication(t *testing.T) {
	fixture := newYarnFixture(t)
	runner := &fakeYarnRunner{}
	for _, raw := range fixture.tarballs {
		if err := os.Remove(raw.Path); err != nil {
			t.Fatal(err)
		}
		break
	}
	_, err := captureFixtureError(t, fixture)
	assertCode(t, err, CodeOfflineInputMissing)
	if runner.starts != 0 {
		t.Fatalf("missing artifact started Yarn %d times", runner.starts)
	}
}

func TestPeerSemverClosedGrammarZeroMajorPrereleaseCompoundAndAmbiguity(t *testing.T) {
	cases := []struct {
		version, spec string
		want          bool
	}{
		{"0.2.3", "^0.2.3", true},
		{"0.2.9", "^0.2.3", true},
		{"0.3.0", "^0.2.3", false},
		{"0.0.3", "^0.0.3", true},
		{"0.0.4", "^0.0.3", false},
		{"1.2.3-beta.1", "1.2.3-beta.1", true},
		{"1.2.3-beta.1", "^1.2.3", false},
		{"1.3.0", ">=1.0.0 <2.0.0", false},
		{"01.2.3", "^1.0.0", false},
	}
	for _, testCase := range cases {
		if got := versionSatisfies(testCase.version, testCase.spec); got != testCase.want {
			t.Errorf("versionSatisfies(%q, %q)=%v want %v", testCase.version, testCase.spec, got, testCase.want)
		}
	}
	packages := []Package{
		{Key: "peer-one", Name: "peer", Version: "1.2.0"},
		{Key: "peer-two", Name: "peer", Version: "1.3.0"},
	}
	if got := resolveUniquePeer("peer", "^1.0.0", packages); got != "" {
		t.Fatalf("ambiguous peer selected %q", got)
	}
}

func TestS03S08N12PrivateMirrorEmptyCacheFrozenOfflineMaterialization(t *testing.T) {
	fixture := newYarnFixture(t)
	if err := os.MkdirAll(filepath.Join(fixture.root, "node_modules", "poison"), 0o700); err != nil {
		t.Fatal(err)
	}
	writeFile(t, filepath.Join(fixture.root, "node_modules", "poison", "package.json"), []byte(`{"name":"poison","version":"9.9.9"}`))
	capture := captureFixture(t, fixture)
	if !reflect.DeepEqual(capture.Evidence.DiscardedDerivedPaths, []string{"node_modules"}) {
		t.Fatalf("ambient installed state was not discarded: %v", capture.Evidence.DiscardedDerivedPaths)
	}
	runner := &fakeYarnRunner{capture: capture}
	runner.context = makeExecutionContext(t, capture, runner)
	mirrorRoot := filepath.Join(t.TempDir(), "private-mirror")
	mirror, err := DerivePrivateMirror(t.Context(), capture, mirrorRoot, filepath.Join(t.TempDir(), "mirror-work"), runner.context)
	if err != nil {
		t.Fatal(err)
	}
	t.Cleanup(func() { _ = makeTreeWritable(mirrorRoot) })
	if len(mirror.Receipt.Files) != 4 || mirror.Receipt.SchemaID != "yarn-classic-private-mirror-receipt-v1" {
		t.Fatalf("unexpected mirror receipt: %+v", mirror.Receipt)
	}
	materialized, err := Materialize(t.Context(), mirror, MaterializeRequest{Destination: filepath.Join(t.TempDir(), "materialized"), WorkRoot: filepath.Join(t.TempDir(), "materialize-work")}, runner.context)
	if err != nil {
		t.Fatal(err)
	}
	if !containsAll(runner.lastInstall.Argv, "install", "--frozen-lockfile", "--offline", "--ignore-scripts", "--non-interactive", "--no-default-rc", "--cache-folder", "--use-yarnrc") {
		t.Fatalf("Yarn install flags incomplete: %v", runner.lastInstall.Argv)
	}
	if runner.lastInstall.Environment["YARN_CACHE_FOLDER"] == "" || runner.lastInstall.Environment["YARN_IGNORE_SCRIPTS"] != "true" || runner.lastInstall.Network != "none" {
		t.Fatalf("Yarn environment/offline authority incomplete: %+v", runner.lastInstall)
	}
	if containsAll(materialized.MaterializedPackages, "node_modules/poison") || !containsAll(materialized.MaterializedPackages, "node_modules/a", "node_modules/b", "node_modules/workspace") {
		t.Fatalf("ambient cache affected materialization: %v", materialized.MaterializedPackages)
	}
	if _, statErr := os.Stat(filepath.Join(materialized.Root, "node_modules", "opt")); !errors.Is(statErr, fs.ErrNotExist) {
		t.Fatalf("target-pruned package was installed: %v", statErr)
	}
	receipt, err := Invoke(t.Context(), materialized, "index.js", []string{"--fixture"}, runner.context)
	if err != nil {
		t.Fatal(err)
	}
	if receipt.AssuranceMode != closureexec.AssurancePortable || runner.starts != 2 {
		t.Fatalf("offline invocation did not use the protected runtime: receipt=%+v starts=%d", receipt, runner.starts)
	}

	if err = makeTreeWritable(mirror.root); err != nil {
		t.Fatal(err)
	}
	if err = os.Remove(filepath.Join(mirror.root, filepath.FromSlash(mirror.Receipt.Files[0].Path))); err != nil {
		t.Fatal(err)
	}
	_, err = Materialize(t.Context(), mirror, MaterializeRequest{Destination: filepath.Join(t.TempDir(), "missing"), WorkRoot: t.TempDir()}, runner.context)
	assertCode(t, err, CodeOfflineInputMissing)
}

func TestClosedParserConfigurationOriginIntegrityAndWorkspaceFailures(t *testing.T) {
	fixture := newYarnFixture(t)
	tests := []struct {
		name string
		code string
		edit func(*ParseRequest)
	}{
		{name: "missing lock", code: CodeLockMissing, edit: func(request *ParseRequest) { request.LockName, request.LockBytes = "", nil }},
		{name: "wrong lock", code: CodeLockFormatUnsupported, edit: func(request *ParseRequest) { request.LockName = "package-lock.json" }},
		{name: "missing integrity", code: CodeIntegrityMissing, edit: func(request *ParseRequest) {
			lines := strings.Split(string(request.LockBytes), "\n")
			for index, line := range lines {
				if strings.HasPrefix(line, "  integrity ") {
					lines = append(lines[:index], lines[index+1:]...)
					break
				}
			}
			request.LockBytes = []byte(strings.Join(lines, "\n"))
		}},
		{name: "mutable origin", code: CodeOriginUnpinned, edit: func(request *ParseRequest) {
			request.LockBytes = []byte(strings.Replace(string(request.LockBytes), "https://registry.yarnpkg.com/a/-/a-1.0.0.tgz#pinned", "git+https://example.invalid/a.git#main", 1))
		}},
		{name: "checksum update config", code: CodeManagerPluginUndeclared, edit: func(request *ParseRequest) {
			request.Configuration = map[string][]byte{".yarnrc": []byte("--update-checksums true\n")}
		}},
		{name: "escaping modules", code: CodeLocalPathEscape, edit: func(request *ParseRequest) {
			request.Configuration = map[string][]byte{".yarnrc": []byte("modules-folder \"../outside\"\n")}
		}},
		{name: "duplicate manifest key", code: CodeLockStale, edit: func(request *ParseRequest) {
			request.Manifests = cloneBytesMap(request.Manifests)
			request.Manifests["package.json"] = []byte(`{"name":"app","name":"shadow","version":"1.0.0"}`)
		}},
		{name: "workspace root not private", code: CodeLockStale, edit: func(request *ParseRequest) {
			var value map[string]any
			_ = json.Unmarshal(request.Manifests["package.json"], &value)
			delete(value, "private")
			request.Manifests = cloneBytesMap(request.Manifests)
			request.Manifests["package.json"] = mustJSON(t, value)
		}},
	}
	for _, testCase := range tests {
		t.Run(testCase.name, func(t *testing.T) {
			request := fixture.request
			testCase.edit(&request)
			_, err := Parse(request)
			assertCode(t, err, testCase.code)
		})
	}

	request := fixture.request
	request.Configuration = map[string][]byte{".yarnrc": []byte("modules-folder \"vendor_modules\"\nworkspaces-experimental true\n")}
	configured, err := Parse(request)
	if err != nil {
		t.Fatal(err)
	}
	if configured.Layout.ModulesFolder != "vendor_modules" || configured.ConfigurationDigest == fixture.graph.ConfigurationDigest || configured.LockDigest == fixture.graph.LockDigest {
		t.Fatalf("layout/configuration identity was not bound: %+v", configured)
	}
}

func TestLockAndConfigurationGrammarRejectsAmbiguousInputs(t *testing.T) {
	fixture := newYarnFixture(t)
	base := string(fixture.request.LockBytes)
	lockCases := []struct {
		name string
		edit func(string) string
		code string
	}{
		{name: "crlf", edit: func(value string) string { return strings.ReplaceAll(value, "\n", "\r\n") }, code: CodeLockFormatUnsupported},
		{name: "missing terminal newline", edit: func(value string) string { return strings.TrimSuffix(value, "\n") }, code: CodeLockFormatUnsupported},
		{name: "tab indentation", edit: func(value string) string { return strings.Replace(value, "  version", "\tversion", 1) }, code: CodeLockFormatUnsupported},
		{name: "header without colon", edit: func(value string) string { return strings.Replace(value, "a@^1.0.0:", "a@^1.0.0", 1) }, code: CodeLockFormatUnsupported},
		{name: "field before entry", edit: func(value string) string { return "  version \"1.0.0\"\n" + value }, code: CodeLockFormatUnsupported},
		{name: "unsupported nested field", edit: func(value string) string {
			return strings.Replace(value, "  version \"1.0.0\"", "  scripts:\n    install \"node install.js\"\n  version \"1.0.0\"", 1)
		}, code: CodeLockFormatUnsupported},
		{name: "duplicate version", edit: func(value string) string {
			return strings.Replace(value, "  version \"1.0.0\"", "  version \"1.0.0\"\n  version \"1.0.0\"", 1)
		}, code: CodeLockFormatUnsupported},
		{name: "unterminated scalar", edit: func(value string) string {
			return strings.Replace(value, "  version \"1.0.0\"", "  version \"1.0.0", 1)
		}, code: CodeLockFormatUnsupported},
		{name: "non exact version", edit: func(value string) string {
			return strings.Replace(value, "  version \"1.0.0\"", "  version \"^1.0.0\"", 1)
		}, code: CodeLockStale},
		{name: "origin outside allowlist", edit: func(value string) string {
			return strings.Replace(value, "https://registry.yarnpkg.com/a/", "https://registry.example.invalid/a/", 1)
		}, code: CodeOriginUnpinned},
	}
	for _, testCase := range lockCases {
		t.Run(testCase.name, func(t *testing.T) {
			request := fixture.request
			request.LockBytes = []byte(testCase.edit(base))
			_, err := Parse(request)
			assertCode(t, err, testCase.code)
		})
	}

	configCases := []struct {
		name, file, value, code string
	}{
		{name: "unsupported file", file: ".yarnrc.yml", value: "nodeLinker: node-modules\n", code: CodeManagerPluginUndeclared},
		{name: "crlf", file: ".yarnrc", value: "workspaces-experimental true\r\n", code: CodeLockFormatUnsupported},
		{name: "invalid line", file: ".yarnrc", value: "modules-folder\n", code: CodeLockFormatUnsupported},
		{name: "disabled workspaces", file: ".yarnrc", value: "workspaces-experimental false\n", code: CodeLockFormatUnsupported},
		{name: "duplicate setting", file: ".yarnrc", value: "modules-folder vendor\nmodules-folder vendor\n", code: CodeLockFormatUnsupported},
	}
	for _, testCase := range configCases {
		t.Run("configuration/"+testCase.name, func(t *testing.T) {
			request := fixture.request
			request.Configuration = map[string][]byte{testCase.file: []byte(testCase.value)}
			_, err := Parse(request)
			assertCode(t, err, testCase.code)
		})
	}
}

func TestMaterializationAPIFailsClosedWithoutExactAuthority(t *testing.T) {
	fixture := newYarnFixture(t)
	capture := captureFixture(t, fixture)
	runner := &fakeYarnRunner{capture: capture}
	authority := makeExecutionContext(t, capture, runner)
	runner.context = authority

	_, err := DerivePrivateMirror(t.Context(), nil, filepath.Join(t.TempDir(), "mirror"), t.TempDir(), authority)
	assertCode(t, err, CodeInputUndeclared)
	_, err = Materialize(t.Context(), nil, MaterializeRequest{Destination: filepath.Join(t.TempDir(), "project"), WorkRoot: t.TempDir()}, authority)
	assertCode(t, err, CodeInputUndeclared)
	_, err = Invoke(t.Context(), nil, "index.js", nil, authority)
	assertCode(t, err, CodeInputUndeclared)
	if _, err = cleanAbsentAbsolute(""); ErrorCode(err) != CodeInputUndeclared {
		t.Fatalf("empty destination error=%v", err)
	}
	existing := t.TempDir()
	if _, err = cleanAbsentAbsolute(existing); ErrorCode(err) != CodeInputUndeclared {
		t.Fatalf("existing destination error=%v", err)
	}

	invalid := *authority
	invalid.Executor = nil
	assertCode(t, validateExecutionContext(&invalid), CodeDerivationUnauthorized)
	invalid = *authority
	invalid.Runtime.C0Checkpoint = nil
	assertCode(t, validateExecutionContext(&invalid), CodeDerivationUnauthorized)
	invalid = *authority
	invalid.Runtime.Manager.VersionOutput = "1.22.21"
	assertCode(t, validateExecutionContext(&invalid), CodeRuntimeIdentityChanged)
	invalid = *authority
	invalid.Runtime.Manager.EntrypointRelativePath = ""
	assertCode(t, validateExecutionContext(&invalid), CodeDerivationUnauthorized)
	assertCode(t, validateExecutionContext(nil), CodeDerivationUnauthorized)
}

func TestPeerRangeReconciliationClosedGrammar(t *testing.T) {
	for _, testCase := range []struct {
		version, spec string
		want          bool
	}{{"1.2.3", "1.2.3", true}, {"1.2.3", "^1.0.0", true}, {"1.2.3", "~1.2.0", true}, {"1.2.3", ">=1.2.0", true}, {"1.2.3", "<1.2.0", false}, {"2.0.0", "^1.0.0", false}, {"1.2.3", "1 || 2", false}, {"bad", ">=1.0.0", false}} {
		if got := versionSatisfies(testCase.version, testCase.spec); got != testCase.want {
			t.Fatalf("versionSatisfies(%q,%q)=%v want=%v", testCase.version, testCase.spec, got, testCase.want)
		}
	}
	packages := []Package{{Key: "a", Name: "peer", Version: "1.2.3"}, {Key: "b", Name: "other", Version: "1.0.0"}}
	if got := resolveUniquePeer("peer", "^1.0.0", packages); got != "a" {
		t.Fatalf("unique peer=%q", got)
	}
	packages = append(packages, Package{Key: "c", Name: "peer", Version: "1.5.0"})
	if got := resolveUniquePeer("peer", "^1.0.0", packages); got != "" {
		t.Fatalf("ambiguous peer=%q", got)
	}
	if (&Error{Code: CodeLockStale}).Error() != CodeLockStale {
		t.Fatal("stable error without detail changed")
	}
}

func TestClosedGrammarHelpersCoverScopedSelectorsWorkspacesAndConditions(t *testing.T) {
	if got := splitComma(`"pkg@one,two", @scope/pkg@^1.0.0`); !reflect.DeepEqual(got, []string{`"pkg@one,two"`, " @scope/pkg@^1.0.0"}) {
		t.Fatalf("quoted selector split=%q", got)
	}
	if _, err := parseSelectorList(`pkg@^1.0.0, pkg@^1.0.0`); err == nil {
		t.Fatal("duplicate selector admitted")
	}
	for _, value := range []string{"pkg", "@scope/pkg"} {
		if !validPackageName(value) {
			t.Fatalf("valid package name rejected: %q", value)
		}
	}
	for _, value := range []string{"", "bad name", "@scope", "@scope/pkg/extra", "pkg@version"} {
		if validPackageName(value) {
			t.Fatalf("invalid package name admitted: %q", value)
		}
	}

	direct, nohoist, err := workspacePatterns(json.RawMessage(`["packages/*"]`))
	if err != nil || !reflect.DeepEqual(direct, []string{"packages/*"}) || len(nohoist) != 0 {
		t.Fatalf("direct workspace declaration=%v/%v err=%v", direct, nohoist, err)
	}
	for _, raw := range []json.RawMessage{json.RawMessage(`"invalid"`), json.RawMessage(`["../escape"]`), json.RawMessage(`{"packages":["packages/*"],"nohoist":["/absolute"]}`)} {
		if _, _, err = workspacePatterns(raw); err == nil {
			t.Fatalf("invalid workspace declaration admitted: %s", raw)
		}
	}
	if !workspaceSpecMatches("1.0.0", "1.0.0", "packages/pkg") || workspaceSpecMatches("^2.0.0", "1.0.0", "packages/pkg") {
		t.Fatal("workspace spec reconciliation changed")
	}

	condition := closuregraph.Condition{EvaluatorID: "yarn-classic-platform-v1", Expression: "os=linux"}
	input := closuregraph.EvaluationInput{Selection: closuregraph.SelectionContext{Markers: map[string]string{"os": "linux"}}}
	if selected, err := evaluateYarnPlatformCondition(condition, input); err != nil || !selected {
		t.Fatalf("platform condition not selected: selected=%v err=%v", selected, err)
	}
	condition.Expression = "os=darwin"
	if selected, err := evaluateYarnPlatformCondition(condition, input); err != nil || selected {
		t.Fatalf("non-matching platform condition selected: selected=%v err=%v", selected, err)
	}
	condition.Expression = "malformed"
	if _, err := evaluateYarnPlatformCondition(condition, input); err == nil {
		t.Fatal("malformed platform condition admitted")
	}

	diagnostic := &Error{Code: CodeLockStale, Detail: "changed", Fields: map[string]string{"path": "package.json"}}
	if ErrorCode(diagnostic) != CodeLockStale || diagnostic.Fields["path"] != "package.json" || ErrorCode(errors.New("plain")) != "" {
		t.Fatalf("structured diagnostic changed: %v code=%q", diagnostic, ErrorCode(diagnostic))
	}
	if !equalStringMap(map[string]string{"a": "1"}, map[string]string{"a": "1"}) || equalStringMap(map[string]string{"a": "1"}, map[string]string{}) || equalStringMap(map[string]string{"a": "1"}, map[string]string{"a": "2"}) {
		t.Fatal("canonical map equality changed")
	}
	metadata := map[string]struct {
		Optional bool `json:"optional"`
	}{"required": {Optional: false}, "optional": {Optional: true}}
	if got := peerOptional(metadata); !reflect.DeepEqual(got, map[string]bool{"optional": true}) {
		t.Fatalf("peer optional projection=%v", got)
	}
}

func TestRealPinnedYarnClassicReadsPrivateMirrorWithEmptyOrdinaryCache(t *testing.T) {
	if _, err := exec.LookPath("yarn"); err != nil {
		t.Skip("Yarn Classic is not installed")
	}
	version, err := exec.Command("yarn", "--version").Output()
	if err != nil || strings.TrimSpace(string(version)) != SupportedYarnVersion {
		t.Skipf("exact Yarn %s is unavailable", SupportedYarnVersion)
	}
	fixture := newYarnFixture(t)
	capture := captureFixture(t, fixture)
	runner := newConcreteYarnRunner(t)
	t.Setenv("YARN_RC_FILENAME", "ambient-yarnrc")
	t.Setenv("YARN_CACHE_FOLDER", filepath.Join(t.TempDir(), "ambient-yarn-cache"))
	t.Setenv("npm_config_cache", filepath.Join(t.TempDir(), "ambient-npm-cache"))
	observe := runner.ProcessLaunchObserver
	runner.ProcessLaunchObserver = func(launch closureexec.ProcessLaunch) {
		poison := []byte("--install.modules-folder ambient_modules\n")
		writeFile(t, filepath.Join(runner.executionRoot, "work", ".yarnrc"), poison)
		home := filepath.Join(launch.CWD, ".curator-home")
		if err := os.MkdirAll(home, 0o700); err != nil {
			t.Fatal(err)
		}
		writeFile(t, filepath.Join(home, ".yarnrc"), poison)
		observe(launch)
	}
	provider := newVerifiedYarnProvider(runner)
	authority := makeVerifiedExecutionContext(t, capture, runner, provider)
	mirrorRoot := filepath.Join(t.TempDir(), "private-mirror")
	mirror, err := DerivePrivateMirror(t.Context(), capture, mirrorRoot, filepath.Join(t.TempDir(), "mirror-work"), authority)
	if err != nil {
		t.Fatal(err)
	}
	t.Cleanup(func() { _ = makeTreeWritable(mirrorRoot) })
	materialized, err := Materialize(t.Context(), mirror, MaterializeRequest{Destination: filepath.Join(t.TempDir(), "materialized"), WorkRoot: filepath.Join(t.TempDir(), "materialize-work")}, authority)
	if err != nil {
		t.Fatalf("real frozen offline Yarn replay through protected executor failed: %v", err)
	}
	for _, installed := range []string{"a", "workspace"} {
		if _, err = os.Stat(filepath.Join(materialized.Root, "node_modules", installed, "package.json")); err != nil {
			t.Fatalf("real Yarn omitted %s: %v", installed, err)
		}
	}
	if _, err = os.Stat(filepath.Join(materialized.Root, "node_modules", "opt")); !errors.Is(err, fs.ErrNotExist) {
		t.Fatalf("real Yarn installed target-pruned optional package: %v", err)
	}
	if len(runner.launches) != 1 || !containsAll(runner.launches[0].Argv, "--no-default-rc", "--offline", "--ignore-scripts") {
		t.Fatalf("real Yarn launch did not use the closed argv: %+v", runner.launches)
	}
	if provider.starts != 1 || provider.lastAudit.Network != "none" {
		t.Fatalf("verified provider did not issue a zero-network audit: starts=%d audit=%+v", provider.starts, provider.lastAudit)
	}
	if capture.Graph.Layout.ModulesFolder != "node_modules" || materialized.capture.Graph.ConfigurationDigest != capture.Graph.ConfigurationDigest {
		t.Fatalf("ambient configuration changed closed layout/identity: layout=%+v config=%s/%s", capture.Graph.Layout, materialized.capture.Graph.ConfigurationDigest, capture.Graph.ConfigurationDigest)
	}
	for _, item := range runner.launches[0].Environment {
		if strings.HasPrefix(item, "PATH=") || strings.HasPrefix(item, "YARN_RC_FILENAME=") || strings.HasPrefix(item, "npm_config_") {
			t.Fatalf("real Yarn launch inherited ambient configuration: %+v", runner.launches[0])
		}
	}
}

type yarnTestRunner interface {
	closureexec.PortableProcessRunner
	RecheckTool(context.Context, nodesource.ToolIdentity) (closureexec.ToolchainIdentity, error)
}

type concreteYarnRunner struct {
	*closureexec.ManagerProcessRunner
	executionRoot, sandboxPath        string
	nodePath, yarnPath                string
	nodeRelative, yarnRelative        string
	nodeDigest, yarnDigest, managerID closuregraph.ID
	launches                          []closureexec.ProcessLaunch
}

func newConcreteYarnRunner(t *testing.T) *concreteYarnRunner {
	t.Helper()
	executionRoot := filepath.Join(t.TempDir(), "execution")
	for _, dir := range []string{"toolchain/node/bin", "toolchain/yarn", "work"} {
		if err := os.MkdirAll(filepath.Join(executionRoot, filepath.FromSlash(dir)), 0o700); err != nil {
			t.Fatal(err)
		}
	}
	nodeCommand, err := exec.LookPath("node")
	if err != nil {
		t.Fatal(err)
	}
	nodePath, err := filepath.EvalSymlinks(nodeCommand)
	if err != nil {
		t.Fatal(err)
	}
	nodePayload, err := os.ReadFile(nodePath) // #nosec G304 -- exact integration tool selected at C0.
	if err != nil {
		t.Fatal(err)
	}
	stagedNode := filepath.Join(executionRoot, "toolchain", "node", "bin", "node")
	if err = os.WriteFile(stagedNode, nodePayload, 0o500); err != nil {
		t.Fatal(err)
	}
	nodeRoot := filepath.Dir(filepath.Dir(nodePath))
	libraries, err := filepath.Glob(filepath.Join(nodeRoot, "lib", "libnode*.dylib"))
	if err != nil {
		t.Fatal(err)
	}
	for _, library := range libraries {
		payload, readErr := os.ReadFile(library) // #nosec G304 -- selected runtime adjacent library.
		if readErr != nil {
			t.Fatal(readErr)
		}
		target := filepath.Join(executionRoot, "toolchain", "node", "lib", filepath.Base(library))
		if err = os.MkdirAll(filepath.Dir(target), 0o700); err != nil {
			t.Fatal(err)
		}
		if err = os.WriteFile(target, payload, 0o400); err != nil {
			t.Fatal(err)
		}
	}
	yarnCommand, err := exec.LookPath("yarn")
	if err != nil {
		t.Fatal(err)
	}
	sandboxPath, err := exec.LookPath("sandbox-exec")
	if err != nil {
		t.Skip("OS-level network-denial harness is unavailable")
	}
	yarnBin, err := filepath.EvalSymlinks(yarnCommand)
	if err != nil {
		t.Fatal(err)
	}
	yarnPackageRoot, err := yarnClassicPackageRoot(yarnBin)
	if err != nil {
		t.Skipf("exact Yarn %s is installed without a supported pinned tool root: %v", SupportedYarnVersion, err)
	}
	stagedYarnRoot := filepath.Join(executionRoot, "toolchain", "yarn")
	if err = copyContainedTreeDereferencingLinks(yarnPackageRoot, yarnPackageRoot, stagedYarnRoot, map[string]bool{}); err != nil {
		t.Fatal(err)
	}
	stagedYarn := filepath.Join(stagedYarnRoot, "bin", "yarn.js")
	yarnPayload, err := os.ReadFile(stagedYarn) // #nosec G304 -- exact staged Yarn entry point.
	if err != nil {
		t.Fatal(err)
	}
	manager, err := closureexec.NewManagerProcessRunner(executionRoot, filepath.Join(executionRoot, "output"))
	if err != nil {
		t.Fatal(err)
	}
	nodeDigest, yarnDigest := digestID(nodePayload), digestID(yarnPayload)
	managerID, err := closuregraph.DomainID("yarn-classic-interpreted-toolchain-v1", map[string]any{"entrypoint_sha256": string(yarnDigest), "node_sha256": string(nodeDigest)})
	if err != nil {
		t.Fatal(err)
	}
	runner := &concreteYarnRunner{ManagerProcessRunner: manager, executionRoot: executionRoot, sandboxPath: sandboxPath, nodePath: stagedNode, yarnPath: stagedYarn, nodeRelative: "toolchain/node/bin/node", yarnRelative: "toolchain/yarn/bin/yarn.js", nodeDigest: nodeDigest, yarnDigest: yarnDigest, managerID: managerID}
	manager.ProcessLaunchObserver = func(launch closureexec.ProcessLaunch) { runner.launches = append(runner.launches, launch) }
	return runner
}

func yarnClassicPackageRoot(yarnBin string) (string, error) {
	candidates := []string{filepath.Join(filepath.Dir(filepath.Dir(yarnBin)), "libexec")}
	if filepath.Base(yarnBin) == "yarn.js" && filepath.Base(filepath.Dir(yarnBin)) == "bin" {
		candidates = append(candidates, filepath.Dir(filepath.Dir(yarnBin)))
	}
	for _, candidate := range candidates {
		entrypoint := filepath.Join(candidate, "bin", "yarn.js")
		if info, err := os.Stat(entrypoint); err == nil && info.Mode().IsRegular() {
			return candidate, nil
		}
	}
	return "", fmt.Errorf("neither Homebrew libexec nor package-root bin/yarn.js exists for %s", yarnBin)
}

func TestYarnClassicPackageRootRecognizesPinnedInstallLayouts(t *testing.T) {
	for _, layout := range []struct {
		name, command, root string
	}{
		{name: "homebrew-libexec", command: "bin/yarn", root: "libexec"},
		{name: "package-root", command: "bin/yarn.js", root: "."},
	} {
		t.Run(layout.name, func(t *testing.T) {
			prefix := t.TempDir()
			root := filepath.Clean(filepath.Join(prefix, layout.root))
			entrypoint := filepath.Join(root, "bin", "yarn.js")
			if err := os.MkdirAll(filepath.Dir(entrypoint), 0o700); err != nil {
				t.Fatal(err)
			}
			if err := os.WriteFile(entrypoint, []byte("fixture"), 0o600); err != nil {
				t.Fatal(err)
			}
			got, err := yarnClassicPackageRoot(filepath.Join(prefix, layout.command))
			if err != nil || got != root {
				t.Fatalf("root=%q err=%v, want %q", got, err, root)
			}
		})
	}
	if _, err := yarnClassicPackageRoot(filepath.Join(t.TempDir(), "bin", "yarn.js")); err == nil {
		t.Fatal("missing pinned Yarn tool root was accepted")
	}
}

func (runner *concreteYarnRunner) Run(ctx context.Context, request closureexec.ExecutionRequest) (closureexec.PortableRunResult, error) {
	if err := prepareFakeExecution(request, runner.executionRoot); err != nil {
		return closureexec.PortableRunResult{}, err
	}
	executable := filepath.Join(runner.executionRoot, filepath.FromSlash(request.Permit.Executable))
	cwd := filepath.Join(runner.executionRoot, filepath.FromSlash(request.Permit.CWD))
	profile := "(version 1) (allow default) (deny network*)"
	args := append([]string{"-p", profile, executable}, request.Permit.Argv...)
	command := exec.CommandContext(ctx, runner.sandboxPath, args...) // #nosec G204 -- exact sandbox, executable, and permit argv.
	command.Dir = cwd
	keys := make([]string, 0, len(request.Permit.Environment))
	for key := range request.Permit.Environment {
		keys = append(keys, key)
	}
	sort.Strings(keys)
	for _, key := range keys {
		command.Env = append(command.Env, key+"="+request.Permit.Environment[key])
	}
	launch := closureexec.ProcessLaunch{Executable: executable, CWD: cwd, Argv: append([]string(nil), request.Permit.Argv...), Environment: append([]string(nil), command.Env...)}
	if runner.ProcessLaunchObserver != nil {
		runner.ProcessLaunchObserver(launch)
	}
	output, err := command.CombinedOutput()
	if err != nil {
		return closureexec.PortableRunResult{}, fmt.Errorf("sandboxed Yarn failed: %w: %s", err, output)
	}
	return portableResult(runner.executionRoot, request.Permit)
}

func (runner *concreteYarnRunner) RecheckTool(_ context.Context, tool nodesource.ToolIdentity) (closureexec.ToolchainIdentity, error) {
	nodePayload, err := os.ReadFile(runner.nodePath) // #nosec G304 -- exact staged Node executable.
	if err != nil || digestID(nodePayload) != runner.nodeDigest {
		return closureexec.ToolchainIdentity{}, fmt.Errorf("selected Node changed: %w", err)
	}
	fingerprint := runner.nodeDigest
	if tool.Role == "package-manager" {
		yarnPayload, readErr := os.ReadFile(runner.yarnPath) // #nosec G304 -- exact staged Yarn entry point.
		if readErr != nil || digestID(yarnPayload) != runner.yarnDigest {
			return closureexec.ToolchainIdentity{}, fmt.Errorf("selected Yarn changed: %w", readErr)
		}
		fingerprint = runner.managerID
	}
	return closureexec.ToolchainIdentity{Fingerprint: fingerprint, ExecutableSHA256: runner.nodeDigest}, nil
}

type verifiedYarnProvider struct {
	runner    *concreteYarnRunner
	identity  closureexec.ProviderIdentity
	receipts  map[string]closureexec.ProviderCapabilityReceipt
	starts    int
	lastAudit closureexec.Audit
}

func newVerifiedYarnProvider(runner *concreteYarnRunner) *verifiedYarnProvider {
	return &verifiedYarnProvider{runner: runner, identity: closureexec.ProviderIdentity{
		Contract: closureexec.VerifiedProviderContractID, ProviderID: "yarn-classic-test-provider", Version: "1.0.0",
		BinarySHA256: digestID([]byte("yarn-classic-test-provider")), TrustEvidence: "test-provider-trust",
	}, receipts: map[string]closureexec.ProviderCapabilityReceipt{}}
}
func (provider *verifiedYarnProvider) Identity() closureexec.ProviderIdentity {
	return provider.identity
}
func (*verifiedYarnProvider) LosslessObservation() bool { return true }
func (provider *verifiedYarnProvider) config() closureexec.AssuranceConfig {
	return closureexec.AssuranceConfig{Mode: closureexec.AssuranceVerified, ProviderID: provider.identity.ProviderID, ProviderVersion: provider.identity.Version, ProviderBinarySHA256: provider.identity.BinarySHA256, ProviderTrustEvidence: provider.identity.TrustEvidence}
}
func (provider *verifiedYarnProvider) Negotiate(_ context.Context, nonce string) (closureexec.ProviderCapabilityReceipt, error) {
	if receipt, ok := provider.receipts[nonce]; ok {
		return receipt, nil
	}
	now := time.Now().UTC()
	receipt := closureexec.ProviderCapabilityReceipt{Provider: provider.identity, Health: "healthy", Nonce: nonce, ObservedAt: now.Add(-time.Second), ExpiresAt: now.Add(time.Minute), Capabilities: []closureexec.CapabilityEvidence{
		{CapabilityID: "total-network-denial-v1", Status: "established"},
		{CapabilityID: "read-only-source-and-toolchain-v1", Status: "established"},
		{CapabilityID: "exact-executable-allowlisting-v1", Status: "established"},
		{CapabilityID: "private-build-root-only-writes-v1", Status: "established"},
		{CapabilityID: "hard-aggregate-descendant-resource-bounds-v1", Status: "established"},
		{CapabilityID: "fail-closed-capability-preflight-v1", Status: "established"},
	}}
	provider.receipts[nonce] = receipt
	return receipt, nil
}
func (provider *verifiedYarnProvider) EnforceAndObserve(ctx context.Context, request closureexec.ExecutionRequest) (closureexec.Audit, error) {
	provider.starts++
	result, err := provider.runner.Run(ctx, request)
	if err != nil {
		return closureexec.Audit{}, err
	}
	defer result.Release()
	evidenceRoot := result.EvidenceRoot
	if evidenceRoot == "" {
		evidenceRoot = result.OutputRoot
	}
	outputs := make([]closureexec.DerivationOutput, len(request.Permit.ExpectedEvidence))
	evidence := make([]string, len(request.Permit.ExpectedEvidence))
	for index, expected := range request.Permit.ExpectedEvidence {
		payload, readErr := os.ReadFile(filepath.Join(evidenceRoot, filepath.FromSlash(expected.Path))) // #nosec G304 -- exact provider-owned evidence path.
		if readErr != nil {
			return closureexec.Audit{}, readErr
		}
		evidence[index] = expected.Path
		outputs[index] = closureexec.DerivationOutput{Path: expected.Path, SchemaID: expected.SchemaID, ArtifactManifestID: expected.ArtifactManifestID, SHA256: digestID(payload), Size: int64(len(payload))}
	}
	audit := closureexec.Audit{Executable: request.Permit.Executable, CWD: request.Permit.CWD, Argv: append([]string(nil), request.Permit.Argv...), Environment: cloneTestStringMap(request.Permit.Environment), Processes: append([]string(nil), request.Permit.AllowedProcesses...), Reads: append([]string(nil), request.Permit.ReadRoots...), Writes: append([]string(nil), request.Permit.WriteRoots...), Evidence: evidence, Network: "none", ExitCode: result.ExitCode, Outputs: outputs}
	provider.lastAudit = audit
	return audit, nil
}

type fakeYarnRunner struct {
	capture     *Capture
	context     *ExecutionContext
	starts      int
	lastInstall closureexec.DerivationPermit
}

func (runner *fakeYarnRunner) RecheckTool(_ context.Context, tool nodesource.ToolIdentity) (closureexec.ToolchainIdentity, error) {
	return closureexec.ToolchainIdentity{Fingerprint: tool.Fingerprint, ExecutableSHA256: tool.ExecutableSHA256}, nil
}

func (runner *fakeYarnRunner) Run(_ context.Context, request closureexec.ExecutionRequest) (closureexec.PortableRunResult, error) {
	runner.starts++
	if err := prepareFakeExecution(request, runner.context.ExecutionRoot); err != nil {
		return closureexec.PortableRunResult{}, err
	}
	permit := request.Permit
	if containsAll(permit.Argv, "install") {
		runner.lastInstall = permit
		cwd := filepath.Join(runner.context.ExecutionRoot, filepath.FromSlash(permit.CWD))
		modules := filepath.Join(cwd, filepath.FromSlash(runner.capture.Graph.Layout.ModulesFolder))
		if err := os.MkdirAll(modules, 0o700); err != nil {
			return closureexec.PortableRunResult{}, err
		}
		for _, pkg := range runner.capture.Graph.Packages {
			if !pkg.Selected || pkg.Key == "workspace:." {
				continue
			}
			target := filepath.Join(modules, filepath.FromSlash(pkg.Name))
			if err := os.MkdirAll(filepath.Dir(target), 0o700); err != nil {
				return closureexec.PortableRunResult{}, err
			}
			if pkg.Resolved == "" {
				_ = os.RemoveAll(target)
				if err := os.Symlink(filepath.Join("..", filepath.FromSlash(pkg.WorkspacePath)), target); err != nil {
					return closureexec.PortableRunResult{}, err
				}
				continue
			}
			if err := os.MkdirAll(target, 0o700); err != nil {
				return closureexec.PortableRunResult{}, err
			}
			if err := extractFixtureTarball(runner.capture.tarballs[pkg.Key], target); err != nil {
				return closureexec.PortableRunResult{}, err
			}
		}
	}
	return portableResult(runner.context.ExecutionRoot, permit)
}

func makeExecutionContext(t *testing.T, capture *Capture, runner yarnTestRunner) *ExecutionContext {
	t.Helper()
	executionRoot := filepath.Join(t.TempDir(), "execution")
	if concrete, ok := runner.(*concreteYarnRunner); ok {
		executionRoot = concrete.executionRoot
	}
	for _, dir := range []string{"bin", "work", "output"} {
		if err := os.MkdirAll(filepath.Join(executionRoot, dir), 0o700); err != nil {
			t.Fatal(err)
		}
	}
	target := capture.Graph.Target
	platform := closuregraph.TargetPlatformPayload{OS: target.OS, Architecture: target.Architecture, ABI: "node", Libc: target.Libc, MinimumRuntime: "bound-by-node-runtime", SDKID: "none", TargetTriple: target.Architecture + "-" + target.OS, Runtime: "node", LanguageModes: map[string]string{"package_manager": "yarn-classic"}, Tuning: map[string]string{}}
	platformNode := closuregraph.Node{Kind: closuregraph.NodeTargetPlatform, LogicalKey: "node.platform.target", Payload: platform}
	platformID, err := platformNode.ID()
	if err != nil {
		t.Fatal(err)
	}
	selection, err := closuregraph.NewSelectionContext(capture.NodeCapture.Graph.RootNodeIDs, map[closuregraph.PlatformRole]closuregraph.ID{closuregraph.PlatformTarget: platformID}, []string{}, target.IncludeDev, map[string]string{"os": target.OS, "architecture": target.Architecture, "cpu": target.Architecture, "libc": target.Libc}, map[string]string{}, []string{"yarn-classic-platform-v1"})
	if err != nil {
		t.Fatal(err)
	}
	tool := func(role, relative, seed, version string) nodesource.ToolIdentity {
		return nodesource.ToolIdentity{Role: role, PolicySelector: role + "-v1", ExecutableRelativePath: relative, VersionOutput: version, PlatformABI: target.OS + "-" + target.Architecture, Fingerprint: digestID([]byte(seed + "-tree")), ExecutableSHA256: digestID([]byte("node-executable")), ExecutionDomain: closuregraph.ExecutionTarget}
	}
	runtime := nodesource.RuntimeBinding{Platform: platform, Node: tool("node-runtime", "bin/node", "node", "v25.6.1"), Manager: tool("package-manager", "bin/node", "yarn", SupportedYarnVersion), TargetNodeIDs: append([]closuregraph.ID(nil), capture.NodeCapture.Graph.RootNodeIDs...)}
	runtime.Node.ReadRoots = []string{"toolchain/node"}
	runtime.Manager.EntrypointRelativePath = "toolchain/yarn/bin/yarn.js"
	runtime.Manager.ReadRoots = []string{"toolchain/node", "toolchain/yarn"}
	if concrete, ok := runner.(*concreteYarnRunner); ok {
		runtime.Node.ExecutableRelativePath = concrete.nodeRelative
		runtime.Node.ExecutableSHA256 = concrete.nodeDigest
		runtime.Node.Fingerprint = concrete.nodeDigest
		runtime.Manager.ExecutableRelativePath = concrete.nodeRelative
		runtime.Manager.EntrypointRelativePath = concrete.yarnRelative
		runtime.Manager.ExecutableSHA256 = concrete.nodeDigest
		runtime.Manager.Fingerprint = concrete.managerID
	}
	c0, err := nodesource.NewC0Checkpoint(capture.NodeCapture, selection, runtime)
	if err != nil {
		t.Fatal(err)
	}
	runtime.C0Checkpoint = &c0
	evaluator := closuregraph.ConditionEvaluatorFunc{EvaluatorID: "yarn-classic-platform-v1", EvaluateFunc: evaluateYarnPlatformCondition}
	_, plan, err := nodesource.Close(capture.NodeCapture, selection, runtime, []closuregraph.ConditionEvaluator{evaluator}, closureexec.PortableExecutionPolicyID)
	if err != nil {
		t.Fatal(err)
	}
	executor, err := closureexec.NewAssuredExecutor(closureexec.DefaultAssuranceConfig(), runner, nil, "test-head")
	if err != nil {
		t.Fatal(err)
	}
	return &ExecutionContext{Executor: executor, Selection: selection, Runtime: runtime, BuildPlan: plan, Recheck: runner.RecheckTool, ExecutionRoot: executionRoot}
}

func makeVerifiedExecutionContext(t *testing.T, capture *Capture, runner *concreteYarnRunner, provider *verifiedYarnProvider) *ExecutionContext {
	t.Helper()
	base := makeExecutionContext(t, capture, runner)
	evaluator := closuregraph.ConditionEvaluatorFunc{EvaluatorID: "yarn-classic-platform-v1", EvaluateFunc: evaluateYarnPlatformCondition}
	_, plan, err := nodesource.Close(capture.NodeCapture, base.Selection, base.Runtime, []closuregraph.ConditionEvaluator{evaluator}, closureexec.VerifiedExecutionPolicyID)
	if err != nil {
		t.Fatal(err)
	}
	executor, err := closureexec.NewAssuredExecutor(provider.config(), nil, provider, "test-head")
	if err != nil {
		t.Fatal(err)
	}
	return &ExecutionContext{Executor: executor, Selection: base.Selection, Runtime: base.Runtime, BuildPlan: plan, Recheck: runner.RecheckTool, ExecutionRoot: base.ExecutionRoot}
}

func prepareFakeExecution(request closureexec.ExecutionRequest, root string) error {
	inputs := map[closuregraph.ID]closureexec.ReplayInput{}
	for _, input := range request.Inputs {
		inputs[input.ReceiptID] = input
		protected, err := input.ProtectedPath()
		if err != nil {
			return err
		}
		target := filepath.Join(root, filepath.FromSlash(input.MountPath))
		_ = os.RemoveAll(target)
		if input.IsTree() {
			if err = os.MkdirAll(filepath.Dir(target), 0o700); err != nil {
				return err
			}
			if err = copyWritableTree(protected, target); err != nil {
				return err
			}
		} else {
			payload, readErr := os.ReadFile(protected)
			if readErr != nil {
				return readErr
			}
			if err = os.MkdirAll(filepath.Dir(target), 0o700); err != nil {
				return err
			}
			if err = os.WriteFile(target, payload, 0o600); err != nil {
				return err
			}
		}
	}
	for _, work := range request.Permit.WorkCopies {
		input := inputs[work.ReceiptID]
		source, err := input.ProtectedPath()
		if err != nil {
			return err
		}
		target := filepath.Join(root, filepath.FromSlash(work.Path))
		_ = os.RemoveAll(target)
		if err = os.MkdirAll(filepath.Dir(target), 0o700); err != nil {
			return err
		}
		if err = copyWritableTree(source, target); err != nil {
			return err
		}
	}
	output := filepath.Join(root, "output")
	_ = os.RemoveAll(output)
	return os.MkdirAll(output, 0o700)
}

func portableResult(executionRoot string, permit closureexec.DerivationPermit) (closureexec.PortableRunResult, error) {
	root := filepath.Join(executionRoot, filepath.FromSlash(permit.Environment["CURATOR_OUTPUT_ROOT"]))
	for _, expected := range permit.ExpectedEvidence {
		path := filepath.Join(root, filepath.FromSlash(expected.Path))
		if err := os.MkdirAll(filepath.Dir(path), 0o700); err != nil {
			return closureexec.PortableRunResult{}, err
		}
		if err := os.WriteFile(path, nil, 0o600); err != nil {
			return closureexec.PortableRunResult{}, err
		}
	}
	return closureexec.PortableRunResult{ExitCode: 0, OutputRoot: root}, nil
}

func captureFixture(t *testing.T, fixture yarnFixture) *Capture {
	t.Helper()
	capture, err := captureFixtureError(t, fixture)
	if err != nil {
		t.Fatal(err)
	}
	return capture
}
func captureFixtureError(t *testing.T, fixture yarnFixture) (*Capture, error) {
	t.Helper()
	storeRoot := filepath.Join(t.TempDir(), "capture-store")
	store, err := closureexec.NewCaptureStore(storeRoot)
	if err != nil {
		t.Fatal(err)
	}
	t.Cleanup(func() { _ = makeTreeWritable(storeRoot) })
	return CaptureAndAdmit(t.Context(), CaptureRequest{Graph: fixture.graph, ProjectRoot: fixture.root, Tarballs: fixture.tarballs, WorkRoot: fixture.work, Store: store, Policy: artifactpolicy.NewService(), PreviousCausalHead: "test-head"})
}

func replaceFixturePackage(t *testing.T, fixture *yarnFixture, name string, pkg fixturePackage) {
	t.Helper()
	payload := buildTGZ(t, pkg)
	sum := sha512.Sum512(payload)
	integrity := "sha512-" + base64.StdEncoding.EncodeToString(sum[:])
	old := packageByName(t, fixture.graph, name)
	rawPath := fixture.tarballs[old.Key].Path
	lock := strings.Replace(string(fixture.request.LockBytes), old.Integrity, integrity, 1)
	fixture.request.LockBytes = []byte(lock)
	writeFile(t, filepath.Join(fixture.root, "yarn.lock"), fixture.request.LockBytes)
	graph, err := Parse(fixture.request)
	if err != nil {
		t.Fatal(err)
	}
	fixture.graph = graph
	replacement := packageByName(t, graph, name)
	writeFile(t, rawPath, payload)
	delete(fixture.tarballs, old.Key)
	delete(fixture.payloads, old.Key)
	fixture.tarballs[replacement.Key] = RawTarball{Path: rawPath}
	fixture.payloads[replacement.Key] = payload
}

func packageByName(t *testing.T, graph Graph, name string) Package {
	t.Helper()
	for _, pkg := range graph.Packages {
		if pkg.Name == name && pkg.Resolved != "" {
			return pkg
		}
	}
	t.Fatalf("package %s not found", name)
	return Package{}
}

func buildTGZ(t *testing.T, pkg fixturePackage) []byte {
	t.Helper()
	metadata := map[string]any{"name": pkg.name, "version": pkg.version}
	for key, value := range pkg.metadata {
		metadata[key] = value
	}
	files := map[string][]byte{"package.json": mustJSON(t, metadata)}
	for name, payload := range pkg.files {
		files[name] = payload
	}
	var output bytes.Buffer
	gz := gzip.NewWriter(&output)
	tw := tar.NewWriter(gz)
	names := make([]string, 0, len(files))
	for name := range files {
		names = append(names, name)
	}
	sort.Strings(names)
	for _, name := range names {
		payload := files[name]
		header := &tar.Header{Name: "package/" + name, Mode: 0o644, Size: int64(len(payload))}
		if err := tw.WriteHeader(header); err != nil {
			t.Fatal(err)
		}
		if _, err := tw.Write(payload); err != nil {
			t.Fatal(err)
		}
	}
	if err := tw.Close(); err != nil {
		t.Fatal(err)
	}
	if err := gz.Close(); err != nil {
		t.Fatal(err)
	}
	return output.Bytes()
}

func extractFixtureTarball(item capturedInput, destination string) error {
	input, err := item.handle.Open()
	if err != nil {
		return err
	}
	defer func() { _ = input.Close() }()
	gz, err := gzip.NewReader(input)
	if err != nil {
		return err
	}
	defer func() { _ = gz.Close() }()
	reader := tar.NewReader(gz)
	for {
		header, err := reader.Next()
		if err == io.EOF {
			return nil
		}
		if err != nil {
			return err
		}
		name := strings.TrimPrefix(filepath.ToSlash(filepath.Clean(header.Name)), "package/")
		if name == "package" || name == "" {
			continue
		}
		target := filepath.Join(destination, filepath.FromSlash(name))
		if err := os.MkdirAll(filepath.Dir(target), 0o700); err != nil {
			return err
		}
		payload, err := io.ReadAll(reader)
		if err != nil {
			return err
		}
		if err := os.WriteFile(target, payload, 0o600); err != nil {
			return err
		}
	}
}

func mustJSON(t *testing.T, value any) []byte {
	t.Helper()
	payload, err := json.Marshal(value)
	if err != nil {
		t.Fatal(err)
	}
	return append(payload, '\n')
}
func writeFile(t *testing.T, path string, payload []byte) {
	t.Helper()
	if err := os.WriteFile(path, payload, 0o600); err != nil {
		t.Fatal(err)
	}
}
func cloneBytesMap(input map[string][]byte) map[string][]byte {
	result := map[string][]byte{}
	for key, value := range input {
		result[key] = append([]byte(nil), value...)
	}
	return result
}
func assertCode(t *testing.T, err error, code string) {
	t.Helper()
	if ErrorCode(err) != code {
		t.Fatalf("error=%v code=%q want=%q", err, ErrorCode(err), code)
	}
}
func cloneTestStringMap(values map[string]string) map[string]string {
	result := make(map[string]string, len(values))
	for key, value := range values {
		result[key] = value
	}
	return result
}

func containsAll(values []string, wanted ...string) bool {
	for _, want := range wanted {
		found := false
		for _, value := range values {
			found = found || value == want
		}
		if !found {
			return false
		}
	}
	return true
}

func makeTreeWritable(root string) error {
	return filepath.WalkDir(root, func(current string, entry fs.DirEntry, walkErr error) error {
		if walkErr != nil {
			return walkErr
		}
		if entry.IsDir() {
			return os.Chmod(current, 0o700)
		}
		return os.Chmod(current, 0o600)
	})
}

func copyWritableTree(source, destination string) error {
	if err := os.Mkdir(destination, 0o700); err != nil {
		return err
	}
	return filepath.WalkDir(source, func(current string, entry fs.DirEntry, walkErr error) error {
		if walkErr != nil {
			return walkErr
		}
		if current == source {
			return nil
		}
		rel, err := filepath.Rel(source, current)
		if err != nil {
			return err
		}
		target := filepath.Join(destination, rel)
		if entry.Type()&fs.ModeSymlink != 0 {
			return fmt.Errorf("test input contains link %s", rel)
		}
		if entry.IsDir() {
			return os.Mkdir(target, 0o700)
		}
		payload, err := os.ReadFile(current) // #nosec G304 -- test-owned tree member.
		if err != nil {
			return err
		}
		return os.WriteFile(target, payload, 0o600)
	})
}
