package rustsource

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"

	"github.com/BurntSushi/toml"
)

const cargoManifestPreamble = `# THIS FILE IS AUTOMATICALLY GENERATED BY CARGO
#
# When uploading crates to the registry Cargo will automatically
# "normalize" Cargo.toml files for maximal compatibility
# with all versions of Cargo and also rewrite ` + "`path`" + ` dependencies
# to registry (e.g., crates.io) dependencies.
#
# If you are reading this file be aware that the original Cargo.toml
# will likely look very different (and much more reasonable).
# See Cargo.toml.orig for the original contents.
`

// normalizeGitManifestV1 is an independent Go port of the closed subset of
// Cargo 0.92 prepare_toml_for_vendor and TomlManifest serialization admitted
// by rust-source-v1. Unsupported value shapes fail closed.
func normalizeGitManifestV1(packageRoot string, selected []string) ([]byte, error) {
	payload, err := os.ReadFile(filepath.Join(packageRoot, "Cargo.toml")) // #nosec G304 -- admitted package root.
	if err != nil {
		return nil, err
	}
	var document map[string]any
	if _, err = toml.Decode(string(payload), &document); err != nil {
		return nil, fail(CodeGitIdentityInvalid, "Git manifest cannot be normalized", nil)
	}
	packageTable, ok := stringAnyMap(document["package"])
	if !ok {
		return nil, fail(CodeGitIdentityInvalid, "Git package table is absent", nil)
	}
	workspacePackage, workspaceResolver, err := findWorkspaceInheritance(packageRoot)
	if err != nil {
		return nil, err
	}
	resolve := func(key string) (any, bool, error) {
		value, exists := packageTable[key]
		if !exists {
			return nil, false, nil
		}
		if table, tableOK := stringAnyMap(value); tableOK {
			workspace, workspaceOK := table["workspace"].(bool)
			if len(table) != 1 || !workspaceOK || !workspace {
				return nil, false, fail(CodeGitIdentityInvalid, "unsupported package inheritance shape", map[string]string{"field": key})
			}
			inherited, inheritedOK := workspacePackage[key]
			if !inheritedOK {
				return nil, false, fail(CodeGitIdentityInvalid, "workspace package field is absent", map[string]string{"field": key})
			}
			return inherited, true, nil
		}
		return value, true, nil
	}
	nameValue, nameOK, err := resolve("name")
	if err != nil || !nameOK {
		return nil, fail(CodeGitIdentityInvalid, "normalized package name is absent", nil)
	}
	name, ok := nameValue.(string)
	if !ok || name == "" {
		return nil, fail(CodeGitIdentityInvalid, "normalized package name is invalid", nil)
	}
	versionValue, versionOK, err := resolve("version")
	if err != nil || !versionOK {
		return nil, fail(CodeGitIdentityInvalid, "normalized package version is absent", nil)
	}
	version, ok := versionValue.(string)
	if !ok || version == "" {
		return nil, fail(CodeGitIdentityInvalid, "normalized package version is invalid", nil)
	}

	var result bytes.Buffer
	result.WriteString(cargoManifestPreamble)
	result.WriteString("\n[package]\n")
	packageOrder := []string{"edition", "rust-version", "name", "version", "authors", "build", "metabuild", "default-target", "forced-target", "links", "exclude", "include", "publish", "workspace", "im-a-teapot"}
	for _, key := range packageOrder {
		value, exists, resolveErr := resolve(key)
		if resolveErr != nil {
			return nil, resolveErr
		}
		if key == "name" {
			value, exists = name, true
		}
		if key == "version" {
			value, exists = version, true
		}
		if key == "workspace" {
			// Cargo's normalized package has already consumed workspace inheritance.
			exists = false
		}
		if key == "build" {
			value, exists = normalizedBuild(value, exists, selected)
		}
		if exists {
			if err = writeTomlAssignment(&result, key, value); err != nil {
				return nil, err
			}
		}
	}
	for _, key := range []string{"autolib", "autobins", "autoexamples", "autotests", "autobenches"} {
		result.WriteString(key + " = false\n")
	}
	for _, key := range []string{"default-run", "description", "homepage", "documentation", "readme", "keywords", "categories", "license", "license-file", "repository"} {
		value, exists, resolveErr := resolve(key)
		if resolveErr != nil {
			return nil, resolveErr
		}
		if key == "readme" && !exists {
			value, exists = false, true
		}
		if exists {
			if err = writeTomlAssignment(&result, key, value); err != nil {
				return nil, err
			}
		}
	}
	if workspaceResolver != "" {
		if err = writeTomlAssignment(&result, "resolver", workspaceResolver); err != nil {
			return nil, err
		}
	}

	selectedSet := map[string]bool{}
	for _, item := range selected {
		selectedSet[item] = true
	}
	if library := normalizedLibrary(document["lib"], name, selectedSet); library != nil {
		writeTargetTable(&result, "lib", *library, false)
	}
	for _, kind := range []string{"bin", "example", "test", "bench"} {
		targets, targetErr := normalizedTargets(kind, document[kind], name, selectedSet)
		if targetErr != nil {
			return nil, targetErr
		}
		for _, target := range targets {
			writeTargetTable(&result, kind, target, true)
		}
	}

	// The supported v1 grammar retains dependency/feature declarations. Using
	// the pinned TOML encoder here is deterministic because all maps are sorted
	// before serialization and unsupported workspace dependency inheritance is
	// rejected by ParseManifest.
	for _, section := range []string{"features", "dependencies", "dev-dependencies", "build-dependencies", "target", "lints"} {
		if value, exists := document[section]; exists {
			encoded, encodeErr := toml.Marshal(map[string]any{section: value})
			if encodeErr != nil {
				return nil, fail(CodeGitIdentityInvalid, "manifest declaration cannot be normalized", map[string]string{"field": section})
			}
			result.WriteByte('\n')
			result.Write(encoded)
		}
	}
	return result.Bytes(), nil
}

func findWorkspaceInheritance(packageRoot string) (map[string]any, string, error) {
	current := filepath.Clean(packageRoot)
	for {
		manifest := filepath.Join(current, "Cargo.toml")
		payload, err := os.ReadFile(manifest) // #nosec G304 -- ancestor manifest search is bounded below repository/package intake in the caller.
		if err == nil {
			var document map[string]any
			if _, err = toml.Decode(string(payload), &document); err != nil {
				return nil, "", err
			}
			if workspace, ok := stringAnyMap(document["workspace"]); ok {
				packageTable, _ := stringAnyMap(workspace["package"])
				resolver, _ := workspace["resolver"].(string)
				if resolver == "" {
					resolver = "1"
				}
				return packageTable, resolver, nil
			}
		}
		parent := filepath.Dir(current)
		if parent == current {
			break
		}
		current = parent
	}
	return map[string]any{}, "", nil
}

func stringAnyMap(value any) (map[string]any, bool) {
	switch table := value.(type) {
	case map[string]any:
		return table, true
	default:
		return nil, false
	}
}

func normalizedBuild(value any, exists bool, selected []string) (any, bool) {
	if exists {
		switch typed := value.(type) {
		case bool:
			return typed, true
		case string:
			return typed, stringSliceContains(selected, filepath.ToSlash(typed))
		case []any:
			kept := []string{}
			for _, item := range typed {
				if pathValue, ok := item.(string); ok && stringSliceContains(selected, filepath.ToSlash(pathValue)) {
					kept = append(kept, pathValue)
				}
			}
			if len(kept) == 1 {
				return kept[0], true
			}
			if len(kept) > 1 {
				return kept, true
			}
		}
	}
	if stringSliceContains(selected, "build.rs") {
		return "build.rs", true
	}
	return false, true
}

type normalizedTarget struct {
	Name, Path string
	Other      map[string]any
}

func normalizedLibrary(raw any, packageName string, selected map[string]bool) *normalizedTarget {
	table, _ := stringAnyMap(raw)
	pathValue, _ := table["path"].(string)
	if pathValue == "" {
		pathValue = "src/lib.rs"
	}
	if !selected[pathValue] {
		return nil
	}
	name, _ := table["name"].(string)
	if name == "" {
		name = strings.ReplaceAll(packageName, "-", "_")
	}
	return &normalizedTarget{Name: name, Path: pathValue, Other: targetOther(table)}
}

func normalizedTargets(kind string, raw any, packageName string, selected map[string]bool) ([]normalizedTarget, error) {
	result := []normalizedTarget{}
	if raw != nil {
		items, ok := raw.([]map[string]any)
		if !ok {
			if generic, genericOK := raw.([]any); genericOK {
				items = make([]map[string]any, 0, len(generic))
				for _, item := range generic {
					table, tableOK := stringAnyMap(item)
					if !tableOK {
						return nil, fail(CodeGitIdentityInvalid, "target declaration is malformed", map[string]string{"kind": kind})
					}
					items = append(items, table)
				}
			} else {
				return nil, fail(CodeGitIdentityInvalid, "target declaration is malformed", map[string]string{"kind": kind})
			}
		}
		for _, table := range items {
			name, _ := table["name"].(string)
			pathValue, _ := table["path"].(string)
			if pathValue == "" && name != "" {
				pathValue = defaultTargetPath(kind, name)
			}
			if name != "" && pathValue != "" && selected[pathValue] {
				result = append(result, normalizedTarget{Name: name, Path: pathValue, Other: targetOther(table)})
			}
		}
	} else if kind == "bin" && selected["src/main.rs"] {
		result = append(result, normalizedTarget{Name: packageName, Path: "src/main.rs", Other: map[string]any{}})
	}
	sort.Slice(result, func(i, j int) bool {
		return result[i].Name+"\x00"+result[i].Path < result[j].Name+"\x00"+result[j].Path
	})
	return result, nil
}

func defaultTargetPath(kind, name string) string {
	switch kind {
	case "bin":
		return "src/bin/" + name + ".rs"
	case "example":
		return "examples/" + name + ".rs"
	case "test":
		return "tests/" + name + ".rs"
	case "bench":
		return "benches/" + name + ".rs"
	default:
		return ""
	}
}

func targetOther(table map[string]any) map[string]any {
	result := map[string]any{}
	for key, value := range table {
		if key != "name" && key != "path" {
			result[key] = value
		}
	}
	return result
}

func writeTargetTable(result *bytes.Buffer, kind string, target normalizedTarget, array bool) {
	result.WriteByte('\n')
	if array {
		result.WriteString("[[" + kind + "]]\n")
	} else {
		result.WriteString("[" + kind + "]\n")
	}
	_ = writeTomlAssignment(result, "name", target.Name)
	_ = writeTomlAssignment(result, "path", target.Path)
	keys := make([]string, 0, len(target.Other))
	for key := range target.Other {
		keys = append(keys, key)
	}
	sort.Strings(keys)
	for _, key := range keys {
		_ = writeTomlAssignment(result, key, target.Other[key])
	}
}

func writeTomlAssignment(result *bytes.Buffer, key string, value any) error {
	result.WriteString(key)
	result.WriteString(" = ")
	switch typed := value.(type) {
	case string:
		result.WriteString(strconv.Quote(typed))
	case bool:
		result.WriteString(strconv.FormatBool(typed))
	case []string:
		result.WriteByte('[')
		for index, item := range typed {
			if index > 0 {
				result.WriteString(", ")
			}
			result.WriteString(strconv.Quote(item))
		}
		result.WriteByte(']')
	case []any:
		result.WriteByte('[')
		for index, item := range typed {
			text, ok := item.(string)
			if !ok {
				return fmt.Errorf("unsupported TOML array for %s", key)
			}
			if index > 0 {
				result.WriteString(", ")
			}
			result.WriteString(strconv.Quote(text))
		}
		result.WriteByte(']')
	default:
		return fail(CodeGitIdentityInvalid, "unsupported normalized manifest value", map[string]string{"field": key})
	}
	result.WriteByte('\n')
	return nil
}
